---
- name: Provision Helper VM
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true

  pre_tasks:
    - name: Debug variables
      debug:
        var: global_bootstrap_details

    - name: Debug variables
      debug:
        var: global_master_details

    - name: Debug variables
      debug:
        var: global_worker_details

  roles:
    - {role: helper_set_dns, tags: dns}
    - {role: helper_set_haproxy, tags: haproxy}
    - {role: helper_set_dhcp, tags: dhcp}
    #- {role: helper_set_quayio, tags: quayio}
    #- {role: helper_set_pxe, tags: pxe}