---
- name: Deploys VM based on cloud image
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true

  tasks:
    - name: install packages
      ansible.builtin.package:
        state: present
        name:
          - tar
          - unzip
          - python3-pip
          - htop
