---
- name: Provision Helper VM
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: true

  #vars:
  #  global_helper_fqdn:
  #  global_helper_hostname:
  #  global_domain:
  #  global_network_cidr:
  #  global_masters:
  #  global_workers:

  tasks:
    - name: install packages
      ansible.builtin.package:
        state: present
        name:
          - tar
          - unzip
          - python3-pip
          - vim
          - wget
          - curl
          - bash-completion
          - tree
          - libselinux-python3
          - firewalld

  roles:
    #- {role: helper_set_quayio, tags: quayio}
    #- {role: helper_set_dns, tags: dns}
    - {role: helper_set_haproxy, tags: haproxy}
    #- {role: helper_set_dhcp, tags: dhcp}
    #- {role: helper_set_pxe, tags: pxe}