---
# handlers file for helper_set_haproxy

- name: Reboot
  ansible.builtin.reboot:
  when: ansible_connection != "local"

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
