---
# tasks file for helper_set_dns
- name: Install bind
  ansible.builtin.package:
    name: 
      - bind
      - bind-utils
    state: present

- name: Write out named file
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/named.conf
  notify:
    - restart bind

- name: Push Serial script
  ansible.builtin.template:
    src: set-dns-serial.sh
    dest: "/usr/local/bin/set-dns-serial.sh"
    mode: '0755'

- name: Set zone serial number
  ansible.builtin.shell: "/usr/local/bin/set-dns-serial.sh"
  register: dymanicserialnumber

- name: Setting serial number as a fact
  ansible.builtin.set_fact:
    serialnumber: "{{ dymanicserialnumber.stdout }}"

- name: Write out zone file
  ansible.builtin.template:
    src: zonefile.j2
    dest: /var/named/zonefile.db
    mode: '0644'
  notify:
    - restart bind

- name: Write out reverse zone file
  ansible.builtin.template:
    src: reverse.j2
    dest: /var/named/reverse.db
    mode: '0644'
  notify:
    - restart bind

- name: Open firewall for DNS service
  ansible.builtin.firewalld:
    service: dns
    permanent: true
    state: enabled

- name: Start and enable named
  ansible.builtin.service:
    name: named
    state: started
    enabled: true

- name: Add IPv4 DNS server addresses
  community.general.nmcli:
    conn_name: "cloud-init eth0"
    type: ethernet
    dns4:
    - "{{ bind_helper_ip}}"
    state: present

- name: Restart service systemd-resolved
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: systemd-resolved
