---
# defaults file for helper_set_haproxy

# Configure stats in HAProxy
haproxy_stats: true
haproxy_stats_port: 9000
haproxy_stats_bind_addr: "0.0.0.0"

# Default setttings for HAProxy.
haproxy_retries: 3
haproxy_timeout_http_request: 10s
haproxy_timeout_connect: 10s
haproxy_timeout_client: 1m
haproxy_timeout_server: 1m
haproxy_timeout_http_keep_alive: 10s
haproxy_timeout_check: 10s
haproxy_maxconn: 3000

haproxy_bootstrap: "bootstrap01.{{ global_domain }}"
haproxy_masters: >-
  [{% for i in range(1, global_masters + 1) %}
    "master{{ '%02d' | format(i) }}"{% if not loop.last %}, {% endif %}
  {% endfor %}]
haproxy_workers: >-
  [{% for i in range(1, global_workers + 1) %}
    "worker{{ '%02d' | format(i) }}"{% if not loop.last %}, {% endif %}
  {% endfor %}]
